Array error
Vetiver/goAPI pull request #2
Opened 2023-10-28 16:02 UTC by Vetiver

2023-10-29 00:41 UTC, lapinn-a requested changes
По последней написанной функции (GetAllNames) вижу прогресс, это круто. И то, что тут 20 тредов, это не значит, что всё плохо. Многие из них обсуждаемые, некоторые пока на данном этапе лучше оставить как есть, но упомянуть о них нужно.

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +    Id   int `json:"id"`
Тут с форматированием проблема (также ниже в этом файле и в других тоже). Вообще VSCode по умолчанию форматирует код на Ctrl+S (так сказано тут: [https://code.visualstudio.com/docs/languages/go#_formatting](https://code.visualstudio.com/docs/languages/go#_formatting)). 
Если это не работает, то хорошо будет разобраться, почему так

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +func Insert(name string) string {
Лучше передавать в аргументах не просто name, а структуру `Data` с заполненным `name`. Так функции будут более схожими, и когда в дальнейшем в `Data` появятся другие поля, не придётся передавать каждое из них как отдельный аргумент.

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +func Insert(name string) string {
Возвращаемым значения лучше сделать не просто `string`, а `(Data, error)`. Это означает, что функция возвращает два значения:
- Если произошла ошибка, возвращается пустую структуру `Data{}` и `error`, не равный `nil`. 
- Если функция завершилась успешно, возвращается заполненная структура `Data` и `error`, равный `nil`

Когда выполняется SQL `INSERT`, мы получаем id созданной записи. Когда будем возвращать структуру `Data`, можно будет сделать `Scan()` в поле структуры `Id`, чтобы вернуть всю информацию о созданном объекте.

Можно возвращать не просто `Data`, а указатель `*Data`, тогда при ошибке она будет `nil`, но пока так не будем делать. 

Зачем вообще возвращать что-то из функции Insert (и Update) — по принципам REST рекомендуется при создании или обновлении объекта в ответе возвращать сам объект. Если так не делать, то клиенту может потребоваться отправлять повторный запрос на сервер для получения созданного/обновлённого объекта.

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
>  	pool := DbStart()
При каждом вызове функций работы с БД тут создаётся новый пул подключений, а это неэффективно. Есть разные способы это исправить, но пока можно не трогать.

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
>  	conn, err := pool.Acquire(context.Background())
Тут забирается соединение из пула, но оно никогда не освобождается. Так как у нас пул каждый раз новый, это  сейчас работает. Но правильно будет добавить после этого `defer`, который отпускает соединение.

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
>  	conn, err := pool.Acquire(context.Background())
Про освобождение соединения (`defer`) см. выше, и ещё нет проверки `err != nil`.

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +func DeliteById(id int) string {
Возвращать можно `(Data, error)` или просто `error`. Я бы и аргументом передавал структуру `Data`, но тут не так это важно.

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +func DeliteById(id int) string {
Опечатка в слове «Delete»

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +	conn, err := pool.Acquire(context.Background())
Про освобождение соединения (`defer`) см. выше (после проверки `err != nil`).

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
>  	conn, err := pool.Acquire(context.Background())
И нет проверки на err != nil, `defer` будет после этой проверки

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +func UpdateName(name string, id int) any {
Тут тоже передавать в аргументах лучше не отдельно значения, а всю структуру, чтобы не разбирать её в хендлерах лишний раз. И очень надеюсь, что `any` тут случайно осталось

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +		"UPDATE test SET name = ? WHERE id = ?", name, id)
PostgreSQL вроде не поддерживает `?` в запросах, так точно работает?

2023-10-29 00:41 UTC, lapinn-a commented on db/db.go
> +	row.Scan()
`Scan` возвращает error, который никуда не присваивается. Следующая проверка `err != nil` проверяет уже проверенную ошибку из строки `conn, err := pool.Acquire(context.Background())`

2023-10-29 00:41 UTC, lapinn-a commented on handlers/InsertName.go
> +	var user User
Дисклеймер: вообще хорошей практикой является разделение типов данных транспорта и БД. Но пока, чтобы было проще и понятнее, в этом примере я предлагаю использовать уже существующий тип. 

У нас уже определена структура `Data` в пакете `db`, поэтому можно и тут использовать её же (`db.Data`).

2023-10-29 00:41 UTC, lapinn-a commented on handlers/InsertName.go
> +	c.JSON(http.StatusOK, db.Insert(user.Name))
Когда будет возвращаться `error` из функции `Insert`, нужно будет добавить обработку ошибок.

2023-10-29 00:41 UTC, lapinn-a commented on handlers/del.go
> +	c.JSON(200, db.DeliteById(intId))
Везде `http.StatusOK`, поэтому тут лучше тоже (или `StatusNoContent`, потому что пустой ответ). И нужна будет обработка ошибок

2023-10-29 00:41 UTC, lapinn-a commented on handlers/getAll.go
> +type Data struct {
Эта структура нигде не используется

2023-10-29 00:41 UTC, lapinn-a commented on handlers/getAll.go
> +	c.JSON(http.StatusOK, parce)
Можно было просто отдать `db.Data` без вложения в `UserGet`. Тогда JSON будет массивом объектов. Но если это намеренно, можно ничего не трогать

2023-10-29 00:41 UTC, lapinn-a commented on handlers/update.go
> +type UpdateData struct {
Про структуры написал выше, можно использовать `db.Data`, пусть может это и не лучшая практика

2023-10-29 00:41 UTC, lapinn-a commented on handlers/update.go
> +	c.JSON(200, db.UpdateName(user.Name, user.Id))
Везде `http.StatusOK`, поэтому тут лучше тоже + нужна проверка ошибок

2023-10-30 08:50 UTC, Vetiver commented on db/db.go
> +    Id   int `json:"id"`
для форматирования я использую Prettier и он исправно сработал(поправил, сори за это)

2023-11-03 19:27 UTC, lapinn-a approved these changes
АППРУВ

2023-11-03 19:29 UTC, merged